module IPaaS
  module Connector
    # Instance of a trigger template.
    #
    # One is created by parsing a (JSON) hash where the `config_mapping` will be resolved
    # and used as the configuration for the trigger.
    class Trigger
      extend IPaaS::Connector::Common::ProcRules::ProcSafe

      proc_safe :provision, :deprovision, :respond_with, :endpoint, :extract_blueprint,
                :trigger_server_url, :trigger_template, :parse

      include IPaaS::Connector::Common::Model
      include IPaaS::Job::Context

      cattr_accessor :trigger_server_url do
        'https://ipaas.com/inbound'
      end

      attr_accessor :runbook
      delegate :version, :account_id, :solution, to: :runbook, allow_nil: true
      delegate :connector, to: :trigger_template, allow_nil: true
      delegate :uuid, to: :runbook

      attribute :description
      attribute :inbound_connection, type: Connection
      attribute :outbound_connection, type: Connection
      attribute :trigger_template, type: TriggerTemplate
      attribute :config_mapping, type: [IPaaS::Connector::Mapping::FieldMapping]
      attribute :blueprint_checksum

      schema :config_schema # deep copy of connection template config schema
      schema :output_schema # deep copy of connection template output schema

      before_validation do |trigger|
        trigger.output_schema&.errors&.clear
      end
      validates :inbound_connection, :trigger_template, presence: { message: "can't be blank." }
      validate :config_mapping_valid?
      validate :outbound_connection_valid?
      validate :blueprint_valid?

      class << self
        def parse(runbook, trigger)
          raise IPaaS::Error, 'Trigger must have a runbook with uuid.' unless runbook.try(:uuid)
          hash = IPaaS::Connector::Common::Serializer.parse(trigger)
          raise IPaaS::Error, 'Trigger must be a hash.' unless hash.is_a?(Hash)
          hash = hash.deep_symbolize_keys

          Trigger.new.tap do |new_trigger|
            copy_trigger_values(new_trigger, hash)
            new_trigger.runbook = runbook
            new_trigger.valid? # triggers resolve
          end
        end

        private

        def copy_trigger_values(trigger, hash)
          trigger.description = hash[:description]
          trigger.blueprint_checksum = hash[:blueprint_checksum]
          trigger.inbound_connection = IPaaS::Connector::Connection.by_uuid(hash.dig(:inbound_connection, :uuid))
          trigger.outbound_connection = IPaaS::Connector::Connection.by_uuid(hash.dig(:outbound_connection, :uuid))
          trigger.trigger_template = IPaaS::Connector::TriggerTemplate.by_uuid(hash.dig(:trigger_template, :uuid))
          trigger.config_mapping = Array(hash[:config_mapping]).map do |cm|
            IPaaS::Connector::Mapping::FieldMapping.parse(cm)
          end
        end
      end

      def to_h_ref
        IPaaS::Connector::Common::Serializer.to_h(self, :description, :blueprint_checksum, :inbound_connection,
                                                  :outbound_connection, :trigger_template, :config_mapping)
      end

      def config(resolve: false)
        return @config if defined?(@config) && !resolve

        config_schema.resolve(self, config_mapping) do |values|
          @config = values
        end
      end

      # Parse the incoming Rack::Request in a couple of steps:
      # 1. Execute the validators of the inbound connection
      # 2. Rewind the request body so the parse function sees it from the start,
      #    even when the validate block read it (e.g. for HMAC verification)
      # 3. Call the trigger_template.parse method to retrieve the output
      # 4. Resolve the output using the trigger_template.output_schema
      # 5. Raise an error in case the output is not conform the output schema
      # 6. Return the output
      def parse_request(request)
        inbound_connection.validate_request(request)
        request.body.rewind
        raw_output = trigger_template.call_function(:parse, self, request)
        raw_output = hash_with_encrypted_secrets(raw_output, output_schema)
        fixed_mapping = IPaaS::Connector::Mapping::FieldMapping.fixed_mapping(raw_output)
        mapped_output = output_schema.resolve(self, fixed_mapping)
        raise IPaaS::Job::FailJob, "Output invalid: #{mapped_output.full_error_messages}" unless mapped_output.valid?

        mapped_output
      end

      # Creates the response to be sent (synchronous response) once the trigger is received.
      # @param request the request received and parsed by the trigger
      # @param job job created based on the request
      # @param response_headers default headers generated by the trigger processor for the response
      # @param context additional metadata or state to pass through the response flow.
      # @return [Hash] containing `status`, `body` and `headers` to be returned to trigger's caller
      def respond_with(request, job, response_headers, context = {})
        context[:request] = request
        context[:trigger_output] = runbook.trigger_output
        context[:job_uuid] = job.uuid.to_s unless job&.uuid.nil?
        default_response = self.prepare_default_response(context, response_headers)
        trigger_template.call_function(:respond_with, self, context, default_response) || default_response
      end

      def prepare_default_response(context, response_headers)
        content = if context[:job_uuid].present?
                    default_response_with_job(context, response_headers)
                  else
                    default_response_no_job(context, response_headers)
                  end
        headers = content[:headers].merge('content-type': content[:content_type])
                                   .with_indifferent_access
        { status: 200, body: content[:body], headers: headers }
      end

      def extract_blueprint
        return if trigger_template.blueprint_filenames.blank?

        blueprint_store.clear!
        self.blueprint_checksum = nil
        trigger_template.call_function(:extract_blueprint, self)
        self.blueprint_checksum = blueprint_store.checksum
      end

      def provision
        trigger_template.call_function(:provision, self)
      end

      def deprovision
        trigger_template.call_function(:deprovision, self)
      end

      def endpoint
        File.join(*[
          self.class.trigger_server_url,
          self.account_id&.to_s,
          self.solution&.uuid&.to_s,
          self.runbook&.uuid&.to_s,
          self.config[:url_postfix]&.to_s,
        ].compact)
      end

      def successor
        runbook&.actions&.detect { |a| a.predecessor_action_reference.nil? }
      end

      def trigger_template=(template)
        @trigger_template = template
        return unless template

        copy_schema_blocks_from(template, :config_schema)
        copy_schema_blocks_from(template, :output_schema)
      end

      private

      def config_mapping_valid?
        return unless trigger_template
        return if IPaaS::Connector::Mapping.invalid_mapping?(self, :config_mapping)
        return if config.valid?

        errors.add(:config_mapping, "invalid: #{config.full_error_messages}")
      end

      def outbound_connection_valid?
        return unless trigger_template&.outbound_traffic
        return if outbound_connection

        errors.add(:outbound_connection, "can't be blank.")
      end

      def blueprint_valid?
        return unless trigger_template&.blueprint_filenames.present?
        return if self.blueprint_checksum

        errors.add(:blueprint_checksum, 'Blueprint files must be extracted to support provisioning.')
      end

      def default_response_no_job(_context, response_headers)
        {
          headers: response_headers,
          content_type: 'text/plain; charset=utf-8',
          body: ' ',
        }
      end

      def default_response_with_job(context, response_headers)
        job_uuid = context[:job_uuid]
        {
          headers: response_headers.merge('x-job-uuid': job_uuid),
          content_type: 'application/json; charset=utf-8',
          body: { job_uuid: job_uuid }.to_json,
        }
      end
    end
  end
end
